project:
  type: website

website:
  title: "Hungjui Yu"
  site-url: "https://yuhungjui.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
  page-footer:
    center: |
      © {{< year >}} Hungjui Yu · Powered by [Quarto](https://quarto.org)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
