project:
  type: website

website:
  title: "Hungjui Yu"
  site-url: "https://yuhungjui.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
  page-footer:
    center: |
      © 2025 Hungjui Yu · Powered by Quarto

format:
  html:
    theme: trestles
    css: styles.css
    toc: true
