project:
  type: website

# Meta
description-meta: "Academic Website by Dr. Hungjui Yu"
author-meta: "Dr. Hungjui Yu"

website:
  title: "Hungjui Yu"
  site-url: "https://yuhungjui.github.io"
  favicon: images/logo_1.png 
  
  navbar:
    logo: images/logo_1.png
    left:
      # - text: "Home"
      #   href: index.qmd
      - text: "Research"
        menu:
        - text: "Projects"
          href: research/projects.qmd
        - text: "Publications"
          href: research/publications.qmd
      - text: "CV"
        href: cv/cv.qmd
    
  search:
    location: navbar
    # type: textbox

  page-footer:
    center: © 2025 Hungjui Yu · Powered by [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=70px}](https://quarto.org/) 

format:
  html:
    theme: sandstone
    # mainfont: Roboto
    # css: styles.css
    # toc: true
    link-external-newwindow: true
    smooth-scroll: true
