project:
  type: website

website:
  title: "Hungjui Yu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  
  page-footer: "© 2025 Your Name"  

format:
  html:
    theme: trestles
      - cosmo
      - brand
    css: styles.css
    toc: true

output-dir: _site

