project:
  type: website

# Meta
description-meta: "Academic Website by Dr. Hungjui Yu"
author-meta: "Dr. Hungjui Yu"

website:
  title: "Hungjui Yu"
  site-url: "https://yuhungjui.github.io"
  favicon: images/logo_1.png 
  
  navbar:
    logo: images/logo_1.png
    left:
      # - text: "Home"
      #   href: index.qmd
      # - text: "Research"
      #   href: research.qmd
      # - text: "Publications"
      #   href: publications.qmd
      - text: "CV"
        href: cv.qmd
    
  search:
    location: navbar
    # type: textbox

  page-footer:
    center: © 2025 Hungjui Yu · Powered by Quarto

format:
  html:
    theme: sandstone
    # css: styles.css
    toc: true
