project:
  type: website

website:
  title: "yuhungjui.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: trestles
      - cosmo
      - brand
    css: styles.css
    toc: true



